In [1]:
!pip3 install ipython-autotime
%load_ext autotime


import pandas as pd
import numpy as np
import re
from tqdm.notebook import tqdm
tqdm.pandas()

from termcolor import colored
import os
# os.environ["TOKENIZERS_PARALLELISM"] = "false"

# nb_workers=10
# my_dir='/content/drive/MyDrive/Next_Door/'


import os
from datetime import datetime
import pickle
import ast
import time

%load_ext autotime

# import pickle5 as pickle

import re
def tag_cleaner(row):
  row = re.sub('@','',row)
  row = re.sub('\++','+',row)
  row = re.sub('-+','-',row)
  row = re.sub('/',' ',row)
  row = re.sub('%','',row)
  row = re.sub('[a-z]','',row)
  return row

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ipython-autotime
  Downloading ipython_autotime-0.3.1-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from ipython-autotime) (7.34.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-autotime) (67.7.2)
Collecting jedi>=0.16 (from ipython->ipython-autotime)
  Downloading jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 24.3 MB/s eta 0:00:00
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-autotime) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-autotime) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-autotime) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-autotime) (3.0.38)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-autotime) (2.14.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-autotime) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-autotime) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-autotime) (4.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython->ipython-autotime) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython->ipython-autotime) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->ipython-autotime) (0.2.6)
Installing collected packages: jedi, ipython-autotime
Successfully installed ipython-autotime-0.3.1 jedi-0.18.2
The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 1.33 s (started: 2023-05-22 18:31:53 +00:00)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
time: 17 s (started: 2023-05-22 18:31:55 +00:00)

In [3]:
!pip3 install googletrans==3.1.0a0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting googletrans==3.1.0a0
  Downloading googletrans-3.1.0a0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting httpx==0.13.3 (from googletrans==3.1.0a0)
  Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 4.6 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2022.12.7)
Collecting hstspreload (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading hstspreload-2023.1.1-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 19.3 MB/s eta 0:00:00
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (1.3.0)
Collecting chardet==3.* (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 12.7 MB/s eta 0:00:00
Collecting idna==2.* (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 5.9 MB/s eta 0:00:00
Collecting rfc3986<2,>=1.3 (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting httpcore==0.9.* (from httpx==0.13.3->googletrans==3.1.0a0)
  Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 4.2 MB/s eta 0:00:00
Collecting h11<0.10,>=0.8 (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0)
  Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 5.6 MB/s eta 0:00:00
Collecting h2==3.* (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0)
  Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 6.6 MB/s eta 0:00:00
Collecting hyperframe<6,>=5.2.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0)
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Collecting hpack<4,>=3.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0)
  Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-3.1.0a0-py3-none-any.whl size=16352 sha256=c219b35572fbbe3031071bc9e4595bbed49d074fa811afe6c65d08e915d127a1
  Stored in directory: /root/.cache/pip/wheels/50/5d/3c/8477d0af4ca2b8b1308812c09f1930863caeebc762fe265a95
Successfully built googletrans
Installing collected packages: rfc3986, hyperframe, hpack, h11, chardet, idna, hstspreload, h2, httpcore, httpx, googletrans
  Attempting uninstall: chardet
    Found existing installation: chardet 4.0.0
    Uninstalling chardet-4.0.0:
      Successfully uninstalled chardet-4.0.0
  Attempting uninstall: idna
    Found existing installation: idna 3.4
    Uninstalling idna-3.4:
      Successfully uninstalled idna-3.4
Successfully installed chardet-3.0.4 googletrans-3.1.0a0 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2023.1.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 idna-2.10 rfc3986-1.5.0
time: 14.8 s (started: 2023-05-22 18:32:12 +00:00)

In [4]:
from googletrans import Translator, constants

time: 550 ms (started: 2023-05-22 18:32:27 +00:00)

# Translate_Meta_Data

In [5]:
def translate_to_english(text):
  translator = Translator()
  translation = translator.translate(text, dest="en")
  print(translation.text)
  return pd.Series([translation.src,translation.text])  

def translate_tags(tags_list_x, language_x):
  if language_x == 'en':
    return tags_list_x.lower()
  else:
    tags_list_x=tags_list_x.split(',')
    tags_list_x_translated = []
    for tag_x in tags_list_x:
      translator = Translator()     
      translation = translator.translate(tag_x, dest="en")
      time.sleep(0.1)
      tags_list_x_translated.append(translation.text.strip().lower())
    tags_list_x_translated = ','.join(tags_list_x_translated)
    print(tags_list_x_translated)
    return tags_list_x_translated

time: 1.2 ms (started: 2023-05-22 18:32:27 +00:00)

In [ ]:
meta_data_df

NameError: ignored

time: 268 ms (started: 2023-05-10 13:33:25 +00:00)

In [ ]:
meta_data_df = pd.read_excel('/content/drive/MyDrive/Kialo vs ChatBots/Meta_Data/Kialo_MetaData_popular.xlsx')
# meta_data_df[['language','claim_translation']] = meta_data_df['initial_claim'].progress_apply(lambda x: translate_to_english(x))
meta_data_df['tags_list_translated'] = meta_data_df.progress_apply(lambda x: translate_tags(tags_list_x=x['tags_list'], language_x=x['language']),axis=1)

meta_data_df

  0%|          | 0/2826 [00:00<?, ?it/s]

justice,violence
github,web,contribution,web function,github,user experience
politics,economics,retirement,health
right,gesellschaft,traffic
coaster
politics,policy,energy
democracy,anarchy,monarchy,epistocracy,republic,government
catalonia,independence,policy
environment,biodiversity,pets
determinism,libertarianism
religion,dominican,republicans,republic,dominican,education
environment
vacasa
pilot,best,comparison,military
economics,policy,capitalism
federalism,italia,centralism
olof palme,palme
hokkien,hakka people,smuggling,pingpu,migrant
greenwill,begreener,environment,green,sustainability
singapore,immigration
politics,m5s,pd,forza italia,lega,electoral polls,elections,votes,berlusconi,surveys,parliament,senate,italia
unemployment,politics,benefits,hungary
platform,participation,collaboration,memory,audiovisual
olof palme,sweden,murder,crimes,the skandian man,palme
argentina,liberal,socialism,economy,capitalism
internet,germany,politics,right,deutschland
québec,independence
czech
mobility,accessibility,access,transport
pma,bioethics,loi
ric,referendum,democracy
program,ideas,proposals,planes,tasks,policies
technology
medicine,medicine,italia,university,studio
travel,climate change
good,godfather,gods,belief,believe
company,government,philosophy,france,french
pollution,digital
politics,colombia
cash
i will,geopolitics,guerre,diplomacy
policy,lula,bolsonaro
slovakia,politics,values
vaccine,vaccination,anti-vaccine,health,disease,prevention
job,sociedad
energy transition,electric car,hydrogen
spain,spain,taxes,taxes,market,mercado
sustainability,climate change,territory,mar,costas
business,politics
gesellschaft,climate change,distribution,production,politics
information
resources,climate,technology,decay,low-tech,sobriety
ancient,greece,culture,effect,society
intelligence,artificial
life imprisonment
politics,m5s,italia,lega,salvini,may,populism,europa,ue,euroscepticism
energy,nuclear
thistimeimvoting,politics,europa
prostitution
afd,germany,deutschland,defense of constitution,politics,right
library,epistemological
revolution,mexico,causes
geopolitics,europe,belgium,france,the netherlands
istanbul,convention,violence,women,homemade,prevention
education,university,studies
musica
vaccines
esperanto,school,education,homework
deutschland,gesellschaft,politics,right
language,nationality,communication,language
italian,language,learning,students
english,french,loi,policy,language,canada,québec
shark,meeting,surf,mer,crisis,policy,ecology
genre
thistimeimvoting,europa,policy
europa,politics,thistimeimvoting
internet,politics,cdu,spd,network,thistimeimvoting
technology,science
climate change,ill
gesellschaft,climate change
gesellschaft,climate change
autos,politics,climate protection
teaching,school,education,education,lehrer,teachers
italia,abruzzo,dump,cerratina
democracy,elections2020,protests
school,parents,children
france
covid-19,coronavirus,pandemic,gesellschaft
pma,gpa,morale,ethics,traffic,mafia
armes,shooting,terrorism,chase,tir
vaccines,covid-19
bge,herd premium,feminism,criticism,gender pay gap,ubi
social media
vaccination,coronavirus
español,life,health
policy,justice,right,ethics,philosophy,democracy
waste,environment,trade,global,conflict,international
existence
energy transition,climate crisis,ill,renewable energy,fossileenergien
polygamy,marriage,couple,amour,conflicts,company
pigeon,fornait,fortnite,mastranquilloquenever
abortion,abortion,right,freedom,fetus
gesellschaft,environment,politics
communication
dab,dab+,norway,norway
violence,film,company,impact,czech
tic,ict,technology
gesellschaft,deutschland,energy,politics
cars,speed,law,limits,car
québec,government,secularism,religion,justice,police
afd,politics
migration pact,austria,politics,right
ferrol,pedestrianization
ecology,economy
austria,politics,law,democracy,tax,right to vote
eu,internet,article 13,europa,politics,right
social
school,short week,weekly plan,saturday-at-home
euro,monetary,policy,frank,gulden
uploadfilter,europa,politics,right,internet
cia,bnd,brain,intelligence,intelligence service,politics
sales,facebook,online
loi,prison
geology,tectonics,emergence
politics,gesellschaft,right,democracy
drugs,latvia
norwegian,norway,hospital,health,policy
tax
venezuela
media,news,taiwan
digital,citizen,damage,control,abuse,safety
socialism
policy,economy,democracy
berlin,public transport,local transport,bahn,train,politics
taiwan,politics
taiwan,politics,president
education,school,digitization
territorial,sustainable
politics,usa,obama,nobel peace prize
ethics,dilemma,social,dignity,seniors,chicanery
ports,economy,transport,navigation
gadgets,technologies,innovation,development,globalization,progress
snuff,finland,parliament,congressman
climate,klimagesetz,eu,climate change,thunberg,deutschland
subject
science,aliens
sohup
education,gadgets,technologies,children
university,activism,protest
elections
nuclear,collapse,collapse,energy,enr,transition
fairmondo,deutschland,deutsch,germany,fairtrade
school,education
teachers
mortal,execution,punishment
assange,whistleblower,wikileaks,germany,deutschland,deutsch
schriesheim,energy,climate change,photovoltaic
language,the definition,meaning,philosophy,philosophy of language
religion,education
chile,policy,constitution,referendum
athos,church,orthodox,sexism
politics
selfie
our globe
bicycle,bicycle brake,rim brake,hub brake,disc brake
education,i|kt
coronavirus,epidemic
coronavirus,covid-19
democracy,elections
pandemic,business,hospital
autonomous driving,future,to,big-data,deichkind,drink driving
education
poland,vote,elections,voting
vaccines
école,future
freedom
g!lt,wahl,name,austria,austria,citizen parliaments
of money,cash
politics
feminism,equality,rights,masculinism,sociedad
socialjustice,homeless,homelessness,social responsibility
contraceptives
3guerramundial,policy,economy
education,inclusive,learn,together,diversity,disability
bitcoin,finance
policy
gesellschaft,nourishment,vegetarian,vegan,health
equipment,covid-19
rights,right,justice
democracy,pursue,yield,employees,property,property
life,nature
privacy,internet
coronavirus,covid-19,mexico
ethics,policy,politics,philosophy,economics,morality
sars-cov-2,coronavirus,masks,mask,covid-19
story
school
europa,education,mint,gewi
the professional study
sciences,social
mathematics
health
education,classroom,tic
artes,arts,contemporary
education,educate,internet,network
convention,citizen,democracy,legislation
organization
international,disney,streaming platforms,globalization,resources,competition
youth,darbs ar jaunatni
frankfurt
legislation,income,universal
education,homework
covid-19,education
philosophy,constitution,freud,sartre,citizenship,pace
history
daria.motta@hotmail.it
welfare,labor,company,motivation,coaching
almetrics,twitter,science,publications,quote
after
coronavirus,ethics,law-abidance
cryptocurrency,bitcoin,currency,economy,regulation,libre
vacation,strand,city
online,virtual,technology,work,future
bge,ubi,basic income
abortion,feminism
online,virtual,technology,work,future
@tedx,lifeonmars,peer to peer,jurisdiction,transhumanism
tics,pedagogy,training,teaching,learning
ruth
policy
health,democracy,covid-19,legislation,freedom,citizenship
chinese teaching
police problem,violence,police
the,conquest,of,space
justice,society
code,car,responsibility,ia,ai,autonomous
financial market,rentism,loan sharking,banks,debt,public
economy,berlin
sports,physics
coronavirus,vaccination
incest
vegetarianism,diet,health,hebrew,in hebrew
europe,diplomacy,multilateralism,geopolitics
virtuality,face-to-face
nuclear,power,politics,policy
gadgets,in,study:,benefit,or,harm
church,italia,state,religion
sexuality,crime,viol
sports,gender,beach volleyball
skepticism
philosophy
gens,default,ethics
hash
ideology,genre,true,mito,theory
groko,coalition,politics,federal government,deutschland,gesellschaft
cloning,dna
elections2021,peru,fujimori,castillo
health,inclusion
assignments,estate,rest,review
music,musica,social
roma
army,pirate,opinion
bitcoin,economy,cryptocurrencies,inversion,blockchain
covid-19,vaccines
transport,youth,mobility,sustainability,security,traffic
whop
education,crèche,enfant,école,burnout,exhaustion
iel,writing,inclusive
nuclear
bi
sexuality,crime,viol
ukraine,russia
politics,justice,referendum
politics,referendum,justice
elections,colombia
cn,oar
economy,market
homo,sapiens,primates
ecology,pacifism,volontary simplicity,solidarity
china
skepticism
education,sciences
culture of cancellation
work
veganism
tics,diversity,inclusion,teaching,leadership,critical thinking

,post_id,title,url,last_edit_date,found_where,initial_claim,tags_list,language,claim_translation,tags_list_translated
0,5637,Pro-Life vs Pro-Choice: Should Abortion be Legal?,https://www.kialo.com/pro-life-vs-pro-choice-s...,2023-03-15T01:58:59.677Z,https://www.kialo.com/explore/popular,Pregnant people should have the right to choos...,"Feminism,Abortion,Health,Religion,Women,Law",en,Pregnant people should have the right to choos...,"feminism,abortion,health,religion,women,law"
1,9563,Should the government provide funding for arts...,https://www.kialo.com/should-the-government-pr...,2023-02-25T19:29:52.672Z,https://www.kialo.com/explore/popular,The government should provide funding for arts...,"Art,Government,Economics,Education",en,The government should provide funding for arts...,"art,government,economics,education"
2,9226,Global overpopulation is a myth.,https://www.kialo.com/global-overpopulation-is...,2023-03-15T12:44:25.910Z,https://www.kialo.com/explore/popular,Global overpopulation is a myth.,"Society,Humans,Earth,Environment,ClimateChange",en,Global overpopulation is a myth.,"society,humans,earth,environment,climatechange"
3,1266,Gender Neutral Bathrooms: Should They be Stand...,https://www.kialo.com/gender-neutral-bathrooms...,2023-03-13T07:21:27.121Z,https://www.kialo.com/explore/popular,All public bathrooms should be gender neutral.,"Gender,Feminism,Transgender,Sex,Equality",en,All public bathrooms should be gender neutral.,"gender,feminism,transgender,sex,equality"
4,9647,Should homeschooling be banned?,https://www.kialo.com/should-homeschooling-be-...,2023-03-14T21:51:02.397Z,https://www.kialo.com/explore/popular,Homeschooling should be banned.,"Education,Policy,USA,Law,School,America",en,Homeschooling should be banned.,"education,policy,usa,law,school,america"
...,...,...,...,...,...,...,...,...,...,...
2821,60719,Культура отмены - путь к прогрессу,https://www.kialo.com/%D0%BA%D1%83%D0%BB%D1%8C...,2022-11-30T10:22:38.173Z,https://www.kialo.com/explore/popular,Культура отмены - путь к прогрессу,Культураотмены,ru,Cancellation culture is the way to progress,culture of cancellation
2822,61035,Нужно ли вводить 4-дневную рабочую неделю?,https://www.kialo.com/%D0%BD%D1%83%D0%B6%D0%BD...,2022-12-19T17:06:26.568Z,https://www.kialo.com/explore/popular,Насколько целесообразна идея ввести 4-х дневну...,Работа,ru,How expedient is the idea to introduce a 4-day...,work
2823,61059,A private money system with real bills and gol...,https://www.kialo.com/a-private-money-system-w...,2023-01-01T23:35:10.607Z,https://www.kialo.com/explore/popular,A private money system with real bills and gol...,Money,en,A private money system with real bills and gol...,money
2824,61106,Веганство:за и против,https://www.kialo.com/%D0%B2%D0%B5%D0%B3%D0%B0...,2022-12-29T05:30:37.694Z,https://www.kialo.com/explore/popular,Веганство:за и против,Веганство,mk,Veganism: pros and cons,veganism
2825,61071,Debatiendo la escuela 🏫,https://www.kialo.com/debatiendo-la-escuela-%F...,2022-12-23T19:38:56.727Z,https://www.kialo.com/explore/popular,Desarrollar el pensamiento crítico en los proc...,"TICs,Diversidad,Inclusion,Docencia,Liderazgo,P...",es,Develop critical thinking in the educational p...,"tics,diversity,inclusion,teaching,leadership,c..."

time: 2min 35s (started: 2023-04-20 13:02:00 +00:00)

In [ ]:
meta_data_df.to_excel('/content/drive/MyDrive/Kialo vs ChatBots/Meta_Data/Kialo_MetaData_popular.xlsx',index=None)

time: 629 ms (started: 2023-04-20 13:05:48 +00:00)

In [ ]:
meta_data_df

,post_id,title,url,last_edit_date,found_where,initial_claim,tags_list,language,claim_translation
0,5637,Pro-Life vs Pro-Choice: Should Abortion be Legal?,https://www.kialo.com/pro-life-vs-pro-choice-s...,2023-03-15T01:58:59.677Z,https://www.kialo.com/explore/popular,Pregnant people should have the right to choos...,"Feminism,Abortion,Health,Religion,Women,Law",en,Pregnant people should have the right to choos...
1,9563,Should the government provide funding for arts...,https://www.kialo.com/should-the-government-pr...,2023-02-25T19:29:52.672Z,https://www.kialo.com/explore/popular,The government should provide funding for arts...,"Art,Government,Economics,Education",en,The government should provide funding for arts...
2,9226,Global overpopulation is a myth.,https://www.kialo.com/global-overpopulation-is...,2023-03-15T12:44:25.910Z,https://www.kialo.com/explore/popular,Global overpopulation is a myth.,"Society,Humans,Earth,Environment,ClimateChange",en,Global overpopulation is a myth.
3,1266,Gender Neutral Bathrooms: Should They be Stand...,https://www.kialo.com/gender-neutral-bathrooms...,2023-03-13T07:21:27.121Z,https://www.kialo.com/explore/popular,All public bathrooms should be gender neutral.,"Gender,Feminism,Transgender,Sex,Equality",en,All public bathrooms should be gender neutral.
4,9647,Should homeschooling be banned?,https://www.kialo.com/should-homeschooling-be-...,2023-03-14T21:51:02.397Z,https://www.kialo.com/explore/popular,Homeschooling should be banned.,"Education,Policy,USA,Law,School,America",en,Homeschooling should be banned.
...,...,...,...,...,...,...,...,...,...
2821,60719,Культура отмены - путь к прогрессу,https://www.kialo.com/%D0%BA%D1%83%D0%BB%D1%8C...,2022-11-30T10:22:38.173Z,https://www.kialo.com/explore/popular,Культура отмены - путь к прогрессу,Культураотмены,ru,Cancellation culture is the way to progress
2822,61035,Нужно ли вводить 4-дневную рабочую неделю?,https://www.kialo.com/%D0%BD%D1%83%D0%B6%D0%BD...,2022-12-19T17:06:26.568Z,https://www.kialo.com/explore/popular,Насколько целесообразна идея ввести 4-х дневну...,Работа,ru,How expedient is the idea to introduce a 4-day...
2823,61059,A private money system with real bills and gol...,https://www.kialo.com/a-private-money-system-w...,2023-01-01T23:35:10.607Z,https://www.kialo.com/explore/popular,A private money system with real bills and gol...,Money,en,A private money system with real bills and gol...
2824,61106,Веганство:за и против,https://www.kialo.com/%D0%B2%D0%B5%D0%B3%D0%B0...,2022-12-29T05:30:37.694Z,https://www.kialo.com/explore/popular,Веганство:за и против,Веганство,mk,Veganism: pros and cons
2825,61071,Debatiendo la escuela 🏫,https://www.kialo.com/debatiendo-la-escuela-%F...,2022-12-23T19:38:56.727Z,https://www.kialo.com/explore/popular,Desarrollar el pensamiento crítico en los proc...,"TICs,Diversidad,Inclusion,Docencia,Liderazgo,P...",es,Develop critical thinking in the educational p...

time: 22.9 ms (started: 2023-04-19 16:18:02 +00:00)

# Translate Query Prompts

In [6]:
import time
def translate_to_english(text,language):
  if language == 'en':
    return text
  else:
    translator = Translator()
    translation = translator.translate(text, dest="en")
    time.sleep(0.1)
    print('\n\n\n\n')
    print(translation.text)
    return translation.text

time: 857 µs (started: 2023-05-22 18:32:27 +00:00)

In [8]:
models = ['gpt-3.5-turbo','text-curie-001','text-babbage-001','text-davinci-001','text-davinci-002','text-davinci-003']
query_types = ['autorlib','economiclean']
query_type = 'questionmark'
query_type = 'proscons'
model = 'gpt-3.5-turbo'

time: 953 µs (started: 2023-05-22 18:33:19 +00:00)

In [10]:
meta_data_df = pd.read_excel('/content/drive/MyDrive/Kialo vs ChatBots/Meta_Data/Kialo_MetaData_popular.xlsx')
# for model in models:
query_file_path = f'/content/drive/MyDrive/Kialo vs ChatBots/Query Results/Kialo - Open AI/kialo_{query_type}_{model}.csv'
# query_file_path = f'/content/drive/MyDrive/Kialo vs ChatBots/Query Results/Kialo - Bing AI/Bing AI Queries Merged - corrected.xlsx'

answers_df = pd.read_csv(query_file_path)
answers_df['language'] = meta_data_df['language']
answers_df['answer_translated'] = answers_df.progress_apply(lambda x: translate_to_english(x['answer'],x['language']),axis=1)
answers_df.to_csv(query_file_path,index=None)
answers_df

  0%|          | 0/2826 [00:00<?, ?it/s]

Pros:
1. Deterrence: The death penalty can act as a deterrent to potential criminals, as they may fear the ultimate punishment for their actions.
2. Justice: Some people believe that the death penalty is a just punishment for certain heinous crimes, such as murder or terrorism.
3. Closure for victims' families: The death penalty can provide closure for the families of victims, who may feel that justice has been served.

Cons:
1. Irreversibility: The death penalty is irreversible, meaning that if an innocent person is wrongly convicted and executed, there is no way to undo the mistake.
2. Human rights: The death penalty is seen by many as a violation of human rights, as it involves taking a life and can be seen as cruel and inhumane.
3. Cost: The death penalty is often more expensive than life imprisonment, due to the lengthy appeals process and the need for specialized legal representation.





Pros:
1. Github is a widely used and popular platform for version control and collaboration, making it easy for developers to contribute to the project.
2. Github provides a robust set of tools for managing code, including issue tracking, pull requests, and code reviews.
3. Github's integration with other tools and services, such as continuous integration and deployment, makes it easy to automate the development process.
4. Github's open-source nature allows for transparency and community involvement in the development process.

Cons:
1. Github may not be the best choice for all projects, depending on the specific needs and requirements of the project.
2. Github's reliance on a centralized server may pose security and privacy concerns for some users.
3. Github's pricing model may be prohibitive for some organizations or individuals, particularly for larger projects or teams.
4. Github's user interface and workflow may not be intuitive for all users, particularly those who are new to version control or collaboration tools.





Pros:
1. The current pension system in France is facing financial challenges due to an aging population and increasing life expectancy. Reforming the system could ensure its sustainability in the long run.
2. A reformed pension system could provide more flexibility and options for individuals to save for their retirement, such as introducing a points-based system or increasing the retirement age.
3. A reformed pension system could also address inequalities in the current system, such as gender and income disparities.

Cons:
1. Any reform to the pension system is likely to face opposition from trade unions and other interest groups, who may see it as a threat to their members' benefits.
2. There is a risk that any reform could lead to a reduction in pension benefits for current and future retirees, which could be seen as unfair.
3. The complexity of the pension system and the potential impact of any reform could make it difficult to implement and could lead to confusion and uncertainty for individuals.





Pros:
- Increased transparency and accountability for the use of traffic radar controls
- Helps drivers to be more aware of potential speed traps and encourages them to drive more safely
- Can lead to a reduction in the number of speeding violations and accidents

Cons:
- May make it easier for drivers to avoid detection and continue to speed
- Could lead to increased traffic congestion as drivers slow down in anticipation of radar controls
- Could be costly and time-consuming for the cities to regularly publish and update the locations of radar controls.





Pros:
- The statement acknowledges that there is room for improvement in France's coaster industry.
- It implies that other European countries have a higher standard for coaster quality and quantity, which could motivate France to strive for better.
- It could spark a conversation about how to improve the coaster industry in France and potentially lead to positive changes.

Cons:
- The statement is a generalization and may not accurately reflect the entire coaster industry in France.
- It does not provide specific evidence or data to support the claim that France is behind other European countries in coaster quality and quantity.
- It could be seen as negative or discouraging towards the coaster industry in France.





Pros:
1. Environmental protection: Moving the natural gas receiving station away from the Taoyuan Datan coral reef coast and waters can help protect the marine ecosystem and reduce the risk of environmental damage caused by accidents or leaks.

2. Public safety: The relocation of the natural gas receiving station can reduce the potential risks to public safety, such as explosions or fires, which can occur in densely populated areas.

3. Economic development: The relocation of the natural gas receiving station can promote the development of other industries in the area, such as tourism, by preserving the natural beauty of the Taoyuan Datan coral reef coast and waters.

Cons:
1. Cost: The relocation of the natural gas receiving station may require significant financial resources, including the construction of new facilities and infrastructure.

2. Time-consuming: The relocation process may take a long time, which can delay the supply of natural gas to the region and affect the energy supply.

3. Opposition from stakeholders: The relocation of the natural gas receiving station may face opposition from stakeholders, such as local residents, environmental groups, and the natural gas industry, who may have different interests and concerns.





Pros:
1. Encourages critical thinking and debate about different forms of government.
2. Allows for the exploration of different political systems and their strengths and weaknesses.
3. Can lead to a better understanding of the role of government in society.
4. Can help identify areas for improvement in existing government systems.
5. Can lead to the development of new and innovative forms of government.

Cons:
1. Can be divisive and lead to political polarization.
2. Can be difficult to reach a consensus on the best form of government.
3. Can lead to the dismissal of existing government systems without fully understanding their complexities.
4. Can be influenced by personal biases and beliefs.
5. Can lead to a lack of action or progress if no agreement is reached.





Pros:
1. Cataluña would have greater control over its own political, economic, and social affairs.
2. Cataluña would be able to establish its own foreign policy and international relations.
3. Cataluña would be able to preserve and promote its unique cultural identity and language.
4. Cataluña would be able to allocate its own resources and funds without interference from the Spanish government.
5. Cataluña would be able to establish its own legal system and judiciary.

Cons:
1. Cataluña would lose the benefits of being part of a larger country, such as access to a larger market and resources.
2. Cataluña would have to establish its own infrastructure, including a military, police force, and government institutions.
3. Cataluña would face economic uncertainty and instability, as it would have to establish its own currency and negotiate trade agreements with other countries.
4. Cataluña would face opposition and potential conflict from the Spanish government and other regions of Spain.
5. Cataluña would have to address the issue of citizenship and immigration, as many people living in Cataluña are not originally from the region.





Pros:
1. Population control: By including cats in the Spanish Catalog of Invasive Alien Species, measures could be taken to control their population and avoid their negative impact on native fauna.

2. Protection of biodiversity: By reducing the population of invasive cats, the biodiversity of Spanish ecosystems would be protected.

3. Prevention of diseases: Invasive cats can transmit diseases to native fauna, so their inclusion in the catalog could help prevent the spread of diseases.

Cons:
1. Sterilization and sacrifice: The inclusion of cats in the Spanish Catalog of Invasive Alien Species could lead to the sterilization and sacrifice of many of them, which could be considered cruel by some.

2. Impact on the domestic cat population: The inclusion of cats in the catalog could have a negative impact on the domestic cat population, since they could be considered invasive and subject to control measures.

3. Lack of scientific evidence: Some argue that there is not enough scientific evidence to show that invasive cats have a negative impact on native fauna, so their inclusion in the catalog might be unnecessary.





As an AI language model, I cannot provide pros and cons for the given statement as it is not clear and specific enough. Please provide more context or information for me to generate a relevant response.





Pros:
1. Separation of the church and the school would allow a more secular and objective education, without religious influences.
2. The separation of church and school could improve the quality of education, since it would focus on teaching practical skills and knowledge instead of religious dogmas.
3. The separation of church and school could foster religious tolerance and cultural diversity in Dominican society.

Cons:
1. The church has played an important role in education in the Dominican Republic for centuries, and the separation could be seen as a threat to the country's tradition and culture.
2. The separation of the church and the school could be seen as a violation of the freedom of religion and expression of Dominican citizens.
3. The separation of church and school could be expensive and difficult to implement, since many schools in the Dominican Republic are affiliated with the church.





Pros:
1. Renewable energy source: Wind turbines generate electricity from a renewable source of energy, which reduces the dependence on fossil fuels and helps to mitigate climate change.
2. Job creation: The construction and maintenance of wind turbines create job opportunities in the local community.
3. Economic benefits: The development of wind energy can bring economic benefits to the region, such as increased tourism and investment.
4. Reduced carbon emissions: Wind energy is a clean source of energy that does not produce greenhouse gas emissions, which helps to reduce carbon emissions and air pollution.

Cons:
1. Visual impact: Wind turbines can be seen as an eyesore and can negatively impact the aesthetic value of the surrounding landscape.
2. Noise pollution: Wind turbines can produce noise pollution, which can be disruptive to nearby residents and wildlife.
3. Wildlife impact: Wind turbines can pose a threat to birds and bats, which can collide with the blades and suffer injury or death.
4. Cost: The construction and maintenance of wind turbines can be expensive, which can lead to higher energy costs for consumers.





As an AI language model, I cannot provide financial or investment advice. It is important to consult with a financial advisor or conduct thorough research before making any investment decisions.





Pros:
1. Greek pilots have a reputation for being highly skilled and experienced, with many years of training and practice.
2. They are known for their ability to handle difficult and challenging situations, such as adverse weather conditions or mechanical failures.
3. Greek pilots are often sought after by airlines and other aviation companies around the world, which can lead to better job opportunities and higher salaries.
4. Their expertise and professionalism can help to improve the safety and efficiency of air travel, benefiting both passengers and the industry as a whole.

Cons:
1. While Greek pilots may be highly skilled, there is no guarantee that they are the best in the world. Other countries and regions may also have highly trained and experienced pilots.
2. The statement may be seen as overly nationalistic or biased, and could be seen as insulting to pilots from other countries.
3. It is possible that the reputation of Greek pilots is based more on anecdotal evidence or cultural stereotypes than on objective data or research.
4. Focusing too much on the nationality of pilots could distract from other important factors that contribute to aviation safety, such as training, technology, and regulations.





As an AI language model, I cannot provide a biased answer as the question of which economic system is better is subjective and depends on individual perspectives and values. However, I can provide some general pros and cons of different economic systems:

Capitalism:
Pros:
- Encourages innovation and entrepreneurship
- Offers consumers a wide range of choices
- Promotes economic growth and development
- Rewards hard work and success

Cons:
- Can lead to income inequality and poverty
- May prioritize profits over social and environmental concerns
- Can result in market failures and economic instability
- May lead to exploitation of workers and resources

Socialism:
Pros:
- Promotes equality and social justice
- Provides universal access to basic needs such as healthcare and education
- Encourages cooperation and community involvement
- Reduces income inequality and poverty

Cons:
- Can lead to inefficiencies and lack of innovation
- May discourage individual initiative and entrepreneurship
- Can result in government corruption and bureaucracy
- May limit personal freedoms and choices

Mixed economy:
Pros:
- Combines the benefits of capitalism and socialism
- Provides a balance between individual freedom and social responsibility
- Offers a safety net for those in need
- Encourages innovation and competition while regulating market excesses

Cons:
- Can be difficult to find the right balance between government intervention and market forces
- May lead to political polarization and conflicts over economic policies
- Can result in inefficiencies and waste if government regulations are too strict or too lax
- May not satisfy the preferences of those who strongly support either capitalism or socialism.





Pros:
1. Greater regional autonomy: a federal system would allow the Italian regions to have greater autonomy in the management of their own resources and policies, without having to depend too much on the central government.
2. Greater representation: a federal system could ensure greater representation of the various Italian regions, allowing them to have greater weight in national politics.
3. Greater political stability: a federal system could guarantee greater political stability, as the regions would have greater powers and responsibilities in the management of their own internal affairs.

Cons:
1. Possible increase in inequality: a federal system could lead to an increase in inequality between the different Italian regions, as some could have greater resources and powers than others.
2. Possible increase in bureaucracy: A federal system could lead to an increase in bureaucracy, as each region would have its own administration and decision-making bodies.
3. Possible increase in conflicts: a federal system could lead to an increase in conflicts between the different Italian regions, as each would have its own interests and priorities.





As an AI language model, I cannot provide pros or cons for this statement as it is related to a sensitive and controversial topic. It is important to respect the ongoing investigation and the opinions of those involved.





Pros:
1. The influx of Han Chinese immigrants from the mainland during the Qing dynasty helped to establish a strong Han Chinese presence in Taiwan, which has contributed to the development of a distinct Taiwanese culture.
2. The Han Chinese immigrants brought with them their language, customs, and traditions, which have enriched the cultural diversity of Taiwan.
3. The Han Chinese immigrants also brought with them their skills and knowledge, which have contributed to the economic development of Taiwan.

Cons:
1. The statement overlooks the fact that Taiwan was already inhabited by indigenous peoples before the arrival of the Han Chinese immigrants, and that their presence and culture have also played a significant role in shaping Taiwanese society.
2. The statement implies that the Han Chinese immigrants were the only or primary factor in the development of Taiwanese society, which ignores the contributions of other groups such as the Japanese and Westerners who have also had an impact on Taiwan's history and culture.
3. The statement may be seen as promoting a narrow and exclusionary view of Taiwanese identity, which could be divisive and harmful to social cohesion.





Without context or information about what "BeGreener" refers to, it is difficult to provide specific pros and cons. Please provide more information.





Pros:
1. Singapore is a developed country with a stable political and economic environment, making it a safe and secure place to live.
2. Singapore has a high standard of living, with excellent healthcare, education, and infrastructure.
3. Singapore is a multicultural society, with a diverse range of people and cultures, making it an interesting and exciting place to live.
4. Singapore has a strong economy, with many job opportunities in various industries.

Cons:
1. The cost of living in Singapore is high, with expensive housing, food, and transportation.
2. The competition for jobs in Singapore is intense, with many highly qualified and skilled workers.
3. Singapore has strict laws and regulations, which may not be suitable for everyone.
4. The influx of immigrants may lead to overcrowding and strain on resources, such as healthcare and education.





As an AI language model, I cannot provide pros and cons for this statement as it is politically biased and goes beyond my capabilities to provide a neutral and objective response. It is important to note that political opinions and preferences are subjective and vary from person to person. It is up to each individual to research and make an informed decision on which political party to vote for based on their own values and beliefs.





Pros:
- It would give people more time to find work, which would improve their economic situation and reduce poverty.
- It would give people more time to train or retrain, which could increase their chances on the labor market.
- It would cost the state less money if people were given assistance for a longer period of time, since fewer people would fall through the system and fewer people would have to apply again and again for assistance.

Cons:
- It would give people less motivation to find work as soon as possible, since they know they can live on welfare for longer.
- It would cost the state more money if people were given assistance for a longer period of time, as more people would fall through the system and more people would have to apply again and again for assistance.
- Giving people the aid for a longer period of time would mean that the state would have less money for other important areas, such as healthcare or education.





As an AI language model, I do not have enough information about "PROJETO BOLHABERTA" to provide pros and cons. Please provide more context or information about the project.





As an AI language model, I cannot provide pros or cons for this statement as it is a serious accusation and a criminal case that has not been officially solved. It is important to respect the legal process and avoid spreading unverified information or rumors.





Pros:
1. Increased economic growth: A more liberal economic policy could lead to increased economic growth, as it would encourage entrepreneurship, investment, and competition.

2. Greater efficiency: A more liberal economic policy could lead to greater efficiency in the allocation of resources, as market forces would determine prices and production levels.


,post_id,url,initial_claim,model,query,answer,created_at,language,answer_translated
0,5637,https://www.kialo.com/pro-life-vs-pro-choice-s...,Pregnant people should have the right to choos...,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. Women have the right to control thei...,1684680193,en,Pros:\n1. Women have the right to control thei...
1,9563,https://www.kialo.com/should-the-government-pr...,The government should provide funding for arts...,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. Encourages creativity and self-expre...,1684680224,en,Pros:\n1. Encourages creativity and self-expre...
2,9226,https://www.kialo.com/global-overpopulation-is...,Global overpopulation is a myth.,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. It challenges the commonly held beli...,1684680253,en,Pros:\n1. It challenges the commonly held beli...
3,1266,https://www.kialo.com/gender-neutral-bathrooms...,All public bathrooms should be gender neutral.,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. Inclusivity: Gender-neutral bathroom...,1684680278,en,Pros:\n1. Inclusivity: Gender-neutral bathroom...
4,9647,https://www.kialo.com/should-homeschooling-be-...,Homeschooling should be banned.,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. Homeschooling may not provide childr...,1684680305,en,Pros:\n1. Homeschooling may not provide childr...
...,...,...,...,...,...,...,...,...,...
2821,60719,https://www.kialo.com/%D0%BA%D1%83%D0%BB%D1%8C...,Культура отмены - путь к прогрессу,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. Encourages accountability and respon...,1684776746,ru,Pros:\n1. Encourages accountability and respon...
2822,61035,https://www.kialo.com/%D0%BD%D1%83%D0%B6%D0%BD...,Насколько целесообразна идея ввести 4-х дневну...,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. Improved work-life balance: A four-d...,1684776770,ru,Pros:\n1. Improved work-life balance: A four-d...
2823,61059,https://www.kialo.com/a-private-money-system-w...,A private money system with real bills and gol...,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. Stability: A private money system wi...,1684776797,en,Pros:\n1. Stability: A private money system wi...
2824,61106,https://www.kialo.com/%D0%B2%D0%B5%D0%B3%D0%B0...,Веганство:за и против,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. Ethical treatment of animals: Vegans...,1684776825,mk,Pros:\n1. Ethical treatment of animals: Vegans...
2825,61071,https://www.kialo.com/debatiendo-la-escuela-%F...,Desarrollar el pensamiento crítico en los proc...,gpt-3.5-turbo,Provide pros and cons for the following statem...,Pros:\n1. Desarrollar el pensamiento crítico e...,1684776852,es,Pros:\n1. Developing critical thinking in stud...

time: 1min 40s (started: 2023-05-22 18:34:20 +00:00)

In [ ]:
answers_df.to_excel(query_file_path,index=None)

time: 944 ms (started: 2023-05-10 14:39:07 +00:00)

In [ ]:
meta_data_df

# Translate Kialo Discussions

In [ ]:
import time
def translate_to_english(text,language):
  if language == 'en':
    return text
  else:
    translator = Translator()
    translation = translator.translate(text, dest="en")
    time.sleep(0.1)
    print('\n\n\n\n')
    print(translation.text)
    return translation.text

time: 1.04 ms (started: 2023-04-25 11:01:04 +00:00)

In [ ]:
meta_data_df = pd.read_excel('/content/drive/MyDrive/Kialo vs ChatBots/Meta_Data/Kialo_MetaData_popular.xlsx')
# for model in models:
# query_file_path = f'/content/drive/MyDrive/Kialo vs ChatBots/Query Results/Kialo - Open AI/kialo_{query_type}_{model}.csv'
query_file_path = f'/content/drive/MyDrive/Kialo vs ChatBots/kialo_popular_tabular_format.hdf'

discussions_df = pd.read_hdf(query_file_path)
# answers_df['language'] = meta_data_df['language']
# answers_df['answer_translated'] = answers_df.progress_apply(lambda x: translate_to_english(x['answer'],x['language']),axis=1)

time: 48.5 s (started: 2023-04-25 11:05:03 +00:00)

In [ ]:
meta_data_df.head(2)
post_2_lang=dict(zip(meta_data_df['post_id'],meta_data_df['language']))
post_2_tags=dict(zip(meta_data_df['post_id'],meta_data_df['tags_list_translated']))

time: 8.26 ms (started: 2023-04-25 11:09:29 +00:00)

In [ ]:
discussions_df['discussion_id'][0]

'17593'

time: 57.1 ms (started: 2023-04-25 11:11:50 +00:00)

In [ ]:
discussions_df = discussions_df[discussions_df['discussion_id'].str.contains(r'\(1\)')==False]
discussions_df = discussions_df[discussions_df['discussion_id'].str.isdigit()]
discussions_df['language']=discussions_df['discussion_id'].astype(int).map(post_2_lang)
discussions_df['tags_list']=discussions_df['discussion_id'].astype(int).map(post_2_tags)
discussions_df

,text_unclean,text,text_index,stance,discussion_id,discussion_name,file_name,stance_to_root,distance_to_root,text_vectorized,all-mpnet-base-v2,language,tags_list
0,1. Blueprints for 3D-printed firearms should b...,Blueprints for 3D-printed firearms should be p...,1.,Topic,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Topic,0,Blueprints for 3D-printed firearms should be p...,"[0.006507655, 0.030841595, 0.009240107, 0.0324...",en,"gun,government,science"
1,1.1. Pro: 3D Printing Makes Illegal Proliferat...,3D Printing Makes Illegal Proliferation of Gun...,1.1.,Pro,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Pro,1,3D Printing Makes Illegal Proliferation of Gun...,"[0.0054019117, 0.044243246, 0.002241348, -0.00...",en,"gun,government,science"
2,1.1.1. Con: It is [notoriously](https://money....,It is [notoriously](https://money.cnn.com/2015...,1.1.1.,Con,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Con,2,It is notoriously easy to buy guns in America....,"[-0.00086407014, 0.052978545, -0.007538742, -0...",en,"gun,government,science"
3,1.1.2. Pro: With 3D Printers even indidividual...,With 3D Printers even indidividuals who wouldn...,1.1.2.,Pro,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Pro,2,With 3D Printers even indidividuals who wouldn...,"[-0.019681752, 0.10858277, 0.008730578, 0.0204...",en,"gun,government,science"
4,1.2. Pro: The opposition to 3D guns is based o...,The opposition to 3D guns is based on the exis...,1.2.,Pro,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Pro,1,The opposition to 3D guns is based on the exis...,"[0.04648163, 0.026524125, 0.011560283, 0.02954...",en,"gun,government,science"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
357825,1.4.3. Con: Negative consequences of acknowled...,Negative consequences of acknowledging the tru...,1.4.3.,Con,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Pro,2,Negative consequences of acknowledging the tru...,"[-0.014781347, 0.038861167, 0.007119923, -0.00...",en,"elections,society,truth,politics"
357826,1.4.3.1. Con: It does if the factors in play r...,It does if the factors in play requires the mi...,1.4.3.1.,Con,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Con,3,It does if the factors in play requires the mi...,"[-0.042287186, 0.048748177, -0.0048393863, -0....",en,"elections,society,truth,politics"
357827,1.5. Con: At the margin one vote makes a diffe...,At the margin one vote makes a difference.,1.5.,Con,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Con,1,At the margin one vote makes a difference.,"[-0.03536318, 0.027356157, -0.0057575637, -0.0...",en,"elections,society,truth,politics"
357828,1.5.1. Pro: In small constituencies an individ...,In small constituencies an individual vote mat...,1.5.1.,Pro,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Con,2,In small constituencies an individual vote mat...,"[-0.03212113, 0.039208263, -0.015957607, 0.005...",en,"elections,society,truth,politics"
357829,1.5.2. Con: This assumes that the margin of sw...,This assumes that the margin of swing between ...,1.5.2.,Con,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Pro,2,This assumes that the margin of swing between ...,"[-0.03891609, 0.02253143, 0.009254736, -0.0125...",en,"elections,society,truth,politics"

time: 1.01 s (started: 2023-04-25 11:36:13 +00:00)

In [ ]:
discussions_df['text_translated'] = discussions_df.progress_apply(lambda x: translate_to_english(x['text'],x['language']),axis=1)

  0%|          | 0/348543 [00:00<?, ?it/s]

Streaming output truncated to the last 5000 lines.

Vinyl music is listened to calmly, sitting in your own home, from the cover you can read the lyrics, the authors, the names of the musicians





The vinyl record never has the same sound, the same music released in other countries, years or with different labels will have many differences to take into account.





Digital music can be listened to anywhere, when doing sports, when traveling and does not require heavy playback supports





Digital music is cheaper, a small media can hold many songs and takes up little space





The music you listen to does not deteriorate over time, the support is not sensitive to dust or light, you do not hear hiss or rumble due to the needle.





To buy music you don't even have to go to a shop but you can do it from the comfort of your home.





The idea of ​​Ancient Greece is harmful to modern Greece





Damage to Modern Greece is caused by questions like this.





Obsession with ancient things prevents us from seeing reality head on





It is in our hands that it does not affect us negatively





It is not in our hands because all the institutions, the culture and the environment are deeply imbued with the problem





This does not mean that our capacity for critical thinking has been nullified





The idea is not harmful, the fact that it has become a product that many neo-Greek populists are pilfering is the essential issue





Ideas don't work like that. OBVIOUSLY we could take it creatively but the power of the idea is generally in the opposite direction in our history so far





Especially in Education, the cult of antiquities leads us to logical dead ends





The reason for this may be that an infallibility is attributed to the Ancient Greeks and the imperfections of the culture in question are rarely emphasized in the education system





There was no "Greece" in ancient times, this jumble of 1500 city-states had absolutely nothing to do with today's country





Indeed, it has nothing to do with it. And if we look at it officially as a state, we are also younger than the United States





In order to find bridges with the ancient world we make leaps which do not allow us to properly analyze the modern world





The stock market will go up 10%+ in the next 12 months \(March 2018\).





Momentum and sentiments are down and hence some more downsides look possible.





You cannot tell the future with 100% accuracy





The stock market's bull market might come to an end as we reach the 10 year mark.





Investor overconfidence is a sign of a market correction.





The stock market has plenty of time in it's boom cycle before the next crash occurs.





The new FED chairman may increase rates more rapidly than previously epected. [bloomberg.com](https://www.bloomberg.com/news/articles/2018-03-21/fed-raises-rates-steepens-path-of-hikes-as-outlook-strengthens)





GDP will continue to grow quickly





Inflation concerns are overblown





Company earnings are going up quickly





Valuations are fair





Valuations are too high





Actually, in a scenario with low interest rates, high PE valuations may be considered fair, especially if earnings will keep growing





Wages are going to go up eating into company earnings





A trade war will happen and deflate stocks





Inflation will increase and impact the market





The Greek university is the best first choice for a modern Greek child





The connection of Greek universities with production is necessarily far behind other developed societies. In the globalized environment we live in, this is a key disadvantage for students. In an almost dead economy, there is no scope for growth.





It is difficult if not impossible, in a country like Greece that puts so much emphasis on the Public and is so poorly organized in the Public sector, for public universities to somehow magically escape and excel.





Unfortunately, both the political leadership and the leadership of the Universities have been comfortable behind a "paternal" relationship and the independence of the Institutions is only on paper. Both the Ministry, from time to time, "plays" with the number of admissions, schools, upgrades, etc., and the HEIs refuse any kind of evaluation, using guild logic.





So we have to find FACTS and comparisons, even if they are skewed or unfair. Otherwise we will never shake them off!





If we do not prefer Greek universities, they will not improve by themselves. \(With the same argument I insisted that my children go to a public and not a private school until now\)





The higher the grades, the less influence the parent or the student himself can have in improving the educational environment. \(My experience so far in kindergarten, elementary and high school shows this.\)





By sending more children to Greek universities we are simply rewarding and supporting the existing situation





Judging the universities by the number and quality of bibliographic references, Greece is much further behind than we think.





I think *in general* we have many Greek \(I mean in Greece\) scientists who are very good at publishing in good journals and conferences and using the average as a tool does them an injustice. Especially compared to countries that are similar in size to ours \(small countries of C and W Europe and W. Balkans\), I think we are doing well in ICT and Life Sciences - especially if you factor in funding and lack of incentives and evaluation.





Lack of motivation \(as the position says above\)





Lack of assessment \(as the position says above\)





It doesn't matter the size of our country. Since children can study wherever they want, why not go wherever is best? By the same token, I don't buy Greek bananas, for example.





If the generalizations and averages are unfair to some notable scientists in Greece, let them find a way to show it. Otherwise it is part of the problem.





It is important for a child to get to know the Greek province \(if he enters outside his city\) and the Greek academic circuit for the future





This is nonsense, If we are to argue about what it offers to get to know a new place better Send the child to study abroad to learn a new language, culture and a thousand and two things, Increasing even the possibility of his professional rehabilitation





The way the Greek family deals with the child studying in the Greek countryside is a subject for a Lanthimos film. Ill situations usually while on the contrary abroad there is a better infrastructure.





Because there are no organized fair and feasible infrastructures, the Greek parent has to do the Greek thing in order to figure out how his child will study. In other words, before he even starts at the university, the damage has already been done, we have taught him that "come on kid", "I have an acquaintance", "X will take care of you" and the whole rotten system that has brought the country to this point.





A similar argument is heard for the army, but in practice the child is simply castrated and prepared to become a chair centaur, a useless citizen in the end.





The university admission system in Greece costs Greek children three "lost" years, creates enormous stress and ultimately does not ensure that the right child will get to the right school





I think the biggest problem is the limited information and the lack of expertise in Greek universities. There is, unfortunately, the general direction that, if you are an excellent student and have written very well, you will give first preference to the computer engineering schools of the NTUA - but if you want to deal with robotics, it is better to declare the School of Production Engineering \( Xanthi\), which "blows" on the given object. It is not possible for all subjects in a school to be at a good level.





Unfortunately, beyond some theoretical knowledge that High School provides, there is no emphasis on skills related to the research process, analytical thinking and problem solving. And there is a big correlation between the school you will study, the profession you will do, and your "social position", which is not confirmed by reality.





Among the other shortcomings of Greek universities is the fact that they have no ability to communicate with their prospective students. They should first of all be interested in getting the right students to the right school!





It is unfair to single out all schools in our assessment. In many universities 1-2 faculties are top while others are lagging behind. Let's choose schools carefully and reward those who do a good job like this.





We necessarily marry them because a university functions as a whole as infrastructure and environment





It is difficult \(because of the admissions system, see related argument\) to "target" a child at a particular school.





Difficult Yes impossible no. It's a computer science course, not molecular biology





It's not just a matter of filling out a form. It's the whole system with the molecules and the molecular subsidies





We are very happy to use some methodology to evaluate specific schools on their own. For example organizations that evaluate universities internationally have extensive dedications to their methodology. eg [timeshighereducation.com](https://www.timeshighereducation.com/world-university-rankings/methodology-world-university-rankings-2018)





I'm afraid that the logic of assessment methods is never going to work for an average Greek HEI \(with the exception perhaps of AUTH which has both theoretical and polytechnic schools\). imho it's like buying a car reading only the NCAP tests, which measure specific things. Again, we have HEIs that have very good faculties and/or individual fields, which are wronged by the leveling style of these ratings - let alone count numbers that do not depend on HEIs





Not all reviews are "style". And the methodology used by the ratings is publicly available.





So why doesn't a Greek university find a methodology to compare SCHOOLS and individuals then?





If it's unfair, why don't the "good" schools do something about it?





Greek pilots are among the best in the world





Because Greek fighter pilots are the best, we also have the best in commercial flights





There is no evidence that we have the best pilots for commercial airlines





Fighter flight has nothing to do with commercial flights





They often come first in NATO exercises





In these exercises, pilots from ALL the participating countries receive distinctions every now and then





These are not measurable elements, usually half-assed and vague





These exercises are very specific to specific scenarios, usually what the pilots of each country have learned





In particular the exercise Red Flag - [en.wikipedia.org](https://en.wikipedia.org/wiki/Exercise_Red_Flag) - which some often refer to, has the purpose "to maximize the combat readiness and survivability of participants by providing a realistic training environment and a pre-flight and post-flight training forum that encourages a free exchange of ideas".





Similar fairy tales come from other countries as well, but we probably need them more and newspapers sometimes publish them.





They are the best because they don't have the best equipment and are forced to patch situations with their brains and skills





Greece spends a surprisingly large part of its GDP on defense.





Many billions are indeed spent on defense spending. They go in submarines that usually tilt.[fromtone.com](http://fromtone.com/bonkers-greek-military-spending-low-tax-revenues-and-weak-agricultural-production/)





They are the best because they make interceptions in the Aegean every day





Interceptions are essentially an expensive play with no impact. Whenever the Turks want, they go wherever they want.





Interceptions are a certain \(very expensive for the Greek public\) dance, they don't learn anything useful so our pilots





We systematically have the best response times in such situations





We neither have such times nor are there any objective evidence to prove it. Surely the Turks will say the same.





Apparently they are the best because since 1820 the Turks have not occupied Greece





It is impossible for country pilots with a logic of appeasing the \(aggressive\) enemy to be anything more than mediocre.





Although I agree with the argument, I think we have no way of knowing what logic our people have and what the Turks have.





Obviously, it's all playing out the same scenario, it can't play out any more. While the Turks are going to Syria, they are fighting from different sides.





It is impossible for the pilots of a country with such a rotten public sector to be better. In the long run this affects their combat effectiveness.





\(Don't make the issue political but a photo of Avramopoulos in an aviator uniform with RayBans playing it like a dude or Panos Kamenos with his back at this point would say it all!\) ? \)





It is impossible for the pilots of a country that has no active fronts to be better. They haven't really fought in many decades actually.





The Turks CONTINUOUSLY have active fronts involving their air force





The "virtual" dogfights in which Greek pilots are involved almost every day are essentially real dogfights that usually end just before the trigger is pulled.





This doesn't make sense. So we pay millions to get some fighters up, which are chased in the air until someone locks on and then he does NOT press the button to launch missiles but says "I won!" and the other fighter retreats;





Sort of, yes, without the comic element.





If things were like this, how and why have Turkish fighters reached Sounio or so often as far as Skyros, etc.?





And how do we know we're "winning" these virtual dogfights? Based on what our pilots are saying to their cougars?





A pilot by himself, in modern warfare is next to nothing. It needs support staff, satellites, information, simulator hours and thousands of other things. Which the Greek pilots don't have.





Indeed, modern air combat is increasingly a matter of technology





It's not just a matter that we don't have the latest technologies in Greece, we also don't have the whole network of technologies required for a fighter pilot to "click" with what is happening on the ground or in the water.





It always comes time for the 1-on-1 showdown/dogfight, and there all the support staff and satellites are pretty much useless, and the outcome is 90% pilot matter.





There is no reason any conflict should involve a 1v1 dogfight. \(Except TopGun in true conflict\)





Even if it's a 1v1 dogfight, it's still not all about the pilot. The aircraft, armament, etc. will play a much bigger role





I have no data on the likelihood of a fight involving a 1-1 dogfight, I'm guessing it's unlikely. It wouldn't make sense in modern warfare, we don't live in the age of "you send your best and I'll send mine to go astray"





They often receive international distinctions disproportionate to the small size of our country.





Rumors, platitudes and picky phrases.





\(If anyone has something SPECIFIC, link, article, text, put it here\)





They excelled in specific exercises





"Disproportionate to the size of the country" is not an argument. As if to say "you play well...for a kid"





There are no publicly available statistics anywhere to prove that Greek pilots are good.





The pilots themselves will OBVIOUSLY support this publicly.





Publicly available lists of "best pilots" in which no Greeks appear. [medium.com](https://medium.com/\@listlar.com/top-10-countries-with-best-air-forces-in-the-world-53633f995fdf) [www.themeshnews.com]( https://www.themeshnews.com/top-10-countries-with-best-air-force-in-the-world-2016/) [igcrankings.fai.org](http://igcrankings.fai.org /) coc





The ministry, the Greek government and state television will OBVIOUSLY support this view for so many years





We have grown up in this climate and find it difficult to judge this issue objectively, we also confuse patriotism. It is not patriotism to be blind to such a matter, however.





Digital competence in schools: A topic for all subjects?





If digitization covers all areas of life, this must also be addressed in all subjects. There are many starting points.





Definitely for all subjects - our project DiBiS [bayernedu.wordpress.com](https://bayernedu.wordpress.com/2018/03/25/alle-dibis-downloads-auf-einen-blick/) tries to get the topic into the bring teacher training.





There must be a general concept that can be applied to all subjects (which may no longer exist as such at some point). It is wrong to isolate this topic, which determines everyday life, in one subject.





Digitization affects all areas of life and should therefore be taught in all subjects.





Most teachers are not digital enough themselves to be able to teach digitalization in their subject.





There should be a subject in which the basic handling of digital and media is taught.





It is important that all teachers let the digital flow naturally into their subjects, as dealing with it is already commonplace and self-evident, but was only learned autodidactically. Handling must be more qualified.





A digitization teacher would have to teach all other subjects digitally as well. That's unrealistic.





It is important that the basics of digital handling are taught in a targeted and focused manner, which is why there must be a separate subject for it.





A digital teacher for all other teachers might help. #Continuing education





There is a danger that a purely digital subject will become too nerdy for all students and can generate little enthusiasm.





The digitization of grammar school classes \(Sec II level\) generates real didactic-pedagogical added value.





The risk of distraction is greater in digital lessons than in conventional ones.





Digitized teaching can motivate teachers to renew and improve their teaching.





What's more: the lessons - at least in relation to the purely frontal communication of content - compete with non-school providers and with informal methods. This sharpens the view for what is really high school: reflection, critical thinking, exchange. A reading tip: [shiftingschool.wordpress.com](https://shiftingschool.wordpress.com/2017/02/17/kritisch-denken-lernen-fuer-alle-kern-der-literacy-von-heute-und- morning/)





The control options for teachers and students are greater in digital lessons than in conventional ones.





Is that true? If digitization is limited to multiple choice or structured exercises on ILIAS, then probably yes. If, on the other hand, digitization means that students acquire research and search routines in a considered manner, are able to independently assess the quality of digital resources or independently generate research questions: then probably no. The second goal can probably not be achieved without a certain degree of freedom.





Practicing digital search and problem-solving strategies enables students to navigate successfully in an increasingly digitized living and business world





Pupils already acquire these skills through their digital socialization, i.e. usually before they start high school and using other content \(games, social media etc.\), which can \(should\) only be embedded in the school context to a limited extent.





Precisely because the digital socialization of the pupils takes place before the grammar school \(and controlled by the financial interests of the providers\), it is important to set a different \(critical\) counter-emphasis at the grammar school level.






In [ ]:
pickle.HIGHEST_PROTOCOL = 4
discussions_df.to_hdf(query_file_path,'df')

<ipython-input-41-cb4853d6c4bf>:2: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block1_values] [items->Index(['text_unclean', 'text', 'text_index', 'stance', 'discussion_id',
       'discussion_name', 'file_name', 'stance_to_root', 'text_vectorized',
       'all-mpnet-base-v2', 'language', 'tags_list', 'text_translated'],
      dtype='object')]

  discussions_df.to_hdf(query_file_path,'df')

time: 19.5 s (started: 2023-04-25 12:29:24 +00:00)

time: 243 ms (started: 2023-04-25 11:32:22 +00:00)

In [ ]:
discussions_df

,text_unclean,text,text_index,stance,discussion_id,discussion_name,file_name,stance_to_root,distance_to_root,text_vectorized,all-mpnet-base-v2,language,tags_list
0,1. Blueprints for 3D-printed firearms should b...,Blueprints for 3D-printed firearms should be p...,1.,Topic,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Topic,0,Blueprints for 3D-printed firearms should be p...,"[0.006507655, 0.030841595, 0.009240107, 0.0324...",NaN,NaN
1,1.1. Pro: 3D Printing Makes Illegal Proliferat...,3D Printing Makes Illegal Proliferation of Gun...,1.1.,Pro,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Pro,1,3D Printing Makes Illegal Proliferation of Gun...,"[0.0054019117, 0.044243246, 0.002241348, -0.00...",NaN,NaN
2,1.1.1. Con: It is [notoriously](https://money....,It is [notoriously](https://money.cnn.com/2015...,1.1.1.,Con,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Con,2,It is notoriously easy to buy guns in America....,"[-0.00086407014, 0.052978545, -0.007538742, -0...",NaN,NaN
3,1.1.2. Pro: With 3D Printers even indidividual...,With 3D Printers even indidividuals who wouldn...,1.1.2.,Pro,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Pro,2,With 3D Printers even indidividuals who wouldn...,"[-0.019681752, 0.10858277, 0.008730578, 0.0204...",NaN,NaN
4,1.2. Pro: The opposition to 3D guns is based o...,The opposition to 3D guns is based on the exis...,1.2.,Pro,17593,3D Printer and Guns: Should Blueprints of 3D-P...,3d-printer-and-guns-should-blueprints-of-3d-pr...,Pro,1,The opposition to 3D guns is based on the exis...,"[0.04648163, 0.026524125, 0.011560283, 0.02954...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
357825,1.4.3. Con: Negative consequences of acknowled...,Negative consequences of acknowledging the tru...,1.4.3.,Con,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Pro,2,Negative consequences of acknowledging the tru...,"[-0.014781347, 0.038861167, 0.007119923, -0.00...",NaN,NaN
357826,1.4.3.1. Con: It does if the factors in play r...,It does if the factors in play requires the mi...,1.4.3.1.,Con,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Con,3,It does if the factors in play requires the mi...,"[-0.042287186, 0.048748177, -0.0048393863, -0....",NaN,NaN
357827,1.5. Con: At the margin one vote makes a diffe...,At the margin one vote makes a difference.,1.5.,Con,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Con,1,At the margin one vote makes a difference.,"[-0.03536318, 0.027356157, -0.0057575637, -0.0...",NaN,NaN
357828,1.5.1. Pro: In small constituencies an individ...,In small constituencies an individual vote mat...,1.5.1.,Pro,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Con,2,In small constituencies an individual vote mat...,"[-0.03212113, 0.039208263, -0.015957607, 0.005...",NaN,NaN
357829,1.5.2. Con: This assumes that the margin of sw...,This assumes that the margin of swing between ...,1.5.2.,Con,6695,Does One Vote Make A Difference?,does-one-vote-make-a-difference-6695.txt,Pro,2,This assumes that the margin of swing between ...,"[-0.03891609, 0.02253143, 0.009254736, -0.0125...",NaN,NaN

time: 70.9 ms (started: 2023-04-25 11:32:28 +00:00)

In [ ]:
discussions_df['discussion_id'][0].isdigit()

True

time: 10.8 ms (started: 2023-04-25 11:26:20 +00:00)